var CONFIG_LANG = {
	"zh":{
		"home": "首页",
		"logout": "注销",
		"published_at": "发布于",
		"new_user": "新用户",
		"welcome": "欢迎光临！",
		"post_blog": "写文章",
		"edit_blog": "编辑文章",
		"category": "分类",
		"categories": "分类",
		"category_input_placeholder": "你可以选择列表中的分类，也可以输入新的分类",
		"tag": "标签",
		"tags": "标签",
		"tag_input_placeholder": "请用空格分开标签",
		"archive": "归档",
		"archives": "归档",
		"subheading_archive": "以下是按年分类的文章归档",
		"subheading_category": "你是什么分类的？",
		"subheading_tag": "希望我的标签个性一点。",
		"blogs_from_cat": "这些文章都属于分类：",
		"blogs_from_tag": "这些文章都属于标签：",
		"config": "配置",
		"configs": "配置",
		"your_uid_is": "你的 uid 是",
		"file": "文件",
		"plese_edit_the_file_in_folder_app": "请修改 app 文件夹里的文件",
		"sitename": "站点名称",
		"username": "站长名",
		"navbar_text": "主页链接文字",
		"sub_title": "小标题",
		"github_account": "Github 用户名",
		"facebook_page": "Facebook 主页链接",
		"twitter_page": "Twitter 主页链接",
		"weibo_account": "微博名",
		"weibo_page": "微博链接",
		"language": "网站语言",
		"sitename_input_placeholder": "请输入站点名称",
		"username_input_placeholder": "请输入站长名",
		"navbar_text_input_placeholder": "请输入主页链接文字",
		"sub_title_input_placeholder": "请输入小标题",
		"github_account_input_placeholder": "请输入Github 用户名",
		"facebook_page_input_placeholder": "请输入Facebook 主页链接",
		"twitter_page_input_placeholder": "请输入Twitter 主页链接",
		"weibo_id_input_placeholder": "请输入微博名",
		"weibo_page_input_placeholder": "请输入微博链接",
		"title_input_placeholder": "请输入标题",
		"language_input_placeholder": "请输入网站语言，如：zh 或者 en",
		"submit": "提交",
		"save": "保存修改",
		"edit": "修改",
		"delete": "删除",
		"login": "登录",
		"email": "邮箱",
		"password": "密码",
		"sign_in": "登录",
		"sign_in_with_github": "使用 Github 账号登录",
		"prev_page": "上一页",
		"next_page": "下一页",
	},
	"en":{
		"home": "HOME",
		"logout": "LOG OUT",
		"published_at": "Published at",
		"new_user": "NEW USER",
		"welcome": "Welcome to Fire Blog!",
		"post_blog": "Post Blog",
		"edit_blog": "Edit Blog",
		"category": "Category",
		"categories": "Categories",
		"category_input_placeholder": "Please select from the list or input a new one",
		"tag": "Tag",
		"tags": "Tags",
		"tag_input_placeholder": "Please seperate tags with space",
		"archive": "Archive",
		"archives": "Archives",
		"subheading_archive": "A year wise archive collection.",
		"subheading_category": "You are categorized as a human : ).",
		"subheading_tag": "What's your tag?",
		"blogs_from_cat": "These blogs belong to cat:",
		"blogs_from_tag": "These blogs belong to tag:",
		"config": "Config",
		"configs": "Configs",
		"your_uid_is": "Your uid is",
		"file": "file",
		"plese_edit_the_file_in_folder_app": "please edit the file in folder app",
		"sitename": "Site Name",
		"username": "Site Owner Name",
		"navbar_text": "Home Page Link Text",
		"sub_title": "Subtitle",
		"github_account": "Github Username",
		"facebook_page": "Facebook Home Page Link",
		"twitter_page": "Twitter Home Page Link",
		"weibo_account": "Weibo ID",
		"weibo_page": "Weibo Home Page Link",
		"language": "Language",
		"sitename_input_placeholder": "Please input Site Name",
		"username_input_placeholder": "Please input Site Owner Name",
		"navbar_text_input_placeholder": "Please input Home Page Link Text",
		"sub_title_input_placeholder": "Please input Subtitle",
		"github_account_input_placeholder": "Please input Github Username",
		"facebook_page_input_placeholder": "Please input Facebook Home Page Link",
		"twitter_page_input_placeholder": "Please input Twitter Home Page Link",
		"weibo_id_input_placeholder": "Please input Weibo ID",
		"weibo_page_input_placeholder": "Please input Weibo Home Page Link",
		"title_input_placeholder": "Please input Title",
		"language_input_placeholder": "Please input your language: zh or en",
		"submit": "Submit",
		"save": "Save",
		"edit": "Edit",
		"delete": "Delete",
		"login": "Log In",
		"email": "Email",
		"password": "Password",
		"sign_in": "Sign In",
		"sign_in_with_github": "Sign in with Github Account",
		"prev_page": "Previous",
		"next_page": "Next",
	}
};