# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'ca' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ca
  platform :ios, "9.0"
  pod 'Transform.swift'
  pod 'Alamofire'
  pod 'Qiniu'
  pod 'CryptoSwift'
  pod 'IDZSwiftCommonCrypto'
  pod 'Wilddog'
  pod 'SwiftValidators'
  pod 'Toast'

  target 'caTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'caUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


